{{- if .Values.monitoring.servicemonitor.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kitchenowl.fullname" . }}-monitoring-auth
  labels:
    {{- include "kitchenowl.labels" . | nindent 4 }}
stringData:
  username: {{ .Values.monitoring.auth.username | quote }}
  password: {{ .Values.monitoring.auth.password | quote }}
{{- end }}
