{{- if and .Values.persistence.recordings.enabled (not .Values.persistence.recordings.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "tvheadend.fullname" . }}-recordings
  labels:
    {{- include "tvheadend.labels" . | nindent 4 }}
spec:
  accessModes:
    {{ toYaml .Values.persistence.recordings.accessModes | indent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.recordings.size | quote }}
  {{- if .Values.persistence.recordings.storageClass }}
  {{- if (eq "-" .Values.persistence.recordings.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: "{{ .Values.persistence.recordings.storageClass }}"
  {{- end }}
  {{- end }}
  {{- if .Values.persistence.recordings.volumeName }}
  volumeName: {{ .Values.persistence.recordings.volumeName }}
  {{- end }}
{{- end }}
