apiVersion: v1
kind: Service
metadata:
  name: {{ template "radarr.fullname" . }}
  labels:
    app: {{ template "radarr.name" . }}
    chart: {{ template "radarr.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 7878
      protocol: TCP
      name: http
  selector:
    app: {{ template "radarr.name" . }}
    release: {{ .Release.Name }}
