{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  annotations: {{ toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  rules:
    - host: {{ index .Values.ingress.hosts 0 | quote }}
      http:
        paths:
          - path: {{ .Values.ingress.hosts[0].paths.path }}
            pathType: {{ .Values.ingress.hosts[0].paths.pathType }}
            backend:
              service:
                name: {{ .Values.service.name }}
                port:
                  number: {{ .Values.servicePort }}
  tls:
    - secretName: {{ .Values.ingress.tls.secretName }}
      hosts:
        - {{ index .Values.ingress.hosts 0 | quote }}
{{- end }}
