apiVersion: v1
kind: Service
metadata:
  name: {{ include "nextpvr.fullname" . }}
  labels:
    {{- include "nextpvr.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
    - name: udp
      port: {{ .Values.service.udpPort }}
      targetPort: udp
      protocol: UDP
  selector:
    {{- include "nextpvr.selectorLabels" . | nindent 4 }}
