apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lgsm.fullname" . }}-env
data:
  LGSM_GAMETYPE: "{{ .Values.game.type }}"
  LGSM_SERVERNAME: "{{ .Values.game.serverName }}"
  LGSM_UPDATEONSTART: "{{ ternary "1" "0" .Values.game.updateOnStart }}"
  {{- range $i, $e := .Values.game.extraEnv }}
  {{ $k := (splitList "=" $e)._0 | upper }}: "{{ (splitList "=" $e)._1 }}"
  {{- end }}
