
{{- if and .Values.persistence.database.enabled (not .Values.persistence.database.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "filesbrowser.fullname" . }}-database
  labels:
    app.kubernetes.io/name: {{ include "filesbrowser.name" . }}
    helm.sh/chart: {{ include "filesbrowser.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  accessModes:
    - {{ .Values.persistence.database.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.database.size | quote }}
{{- if .Values.persistence.database.storageClass }}
{{- if (eq "-" .Values.persistence.database.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistence.database.storageClass }}"
{{- end }}
{{- end }}
{{- end -}}
