apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mikrotik-exporter.fullname" . }}
  labels:
    {{- include "mikrotik-exporter.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- .Values.config | toYaml | nindent 4 }}
