apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mikrotik-exporter.fullname" . }}
  labels:
    {{- include "mikrotik-exporter.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "mikrotik-exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mikrotik-exporter.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mikrotik-exporter.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        ports:
          - name: http
            containerPort: 49090
            protocol: TCP
        args:
          - --cfg-dir
          - /mktxp_config
          - export
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
        volumeMounts:
          - name: {{ include "mikrotik-exporter.fullname" . }}
            mountPath: /mktxp_config
      volumes:
        - name: {{ include "mikrotik-exporter.fullname" . }}
          secret:
            secretName: {{ include "mikrotik-exporter.fullname" . }}
