apiVersion: v1
kind: Secret
metadata:
    name: {{ include "mikrotik-exporter.fullname" . }}
    labels:
    {{- include "mikrotik-exporter.labels" . | nindent 4 }}
type: Opaque
data:
   _mktxp.conf: {{ .Values._mktxp_conf | b64enc | quote }}
   mktxp.conf: {{ .Values.mktxp_conf | b64enc | quote }}